# Copyright 2019-2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#
#
# Tests for src/dsp.

load("//:defs.bzl", "c_test")

package(licenses = ["notice"])

c_test(
    name = "auto_gain_control_test",
    srcs = ["auto_gain_control_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "biquad_filter_test",
    srcs = ["biquad_filter_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "butterworth_test",
    srcs = ["butterworth_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "channel_map_test",
    srcs = ["channel_map_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "complex_test",
    srcs = ["complex_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "convert_sample_test",
    srcs = ["convert_sample_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "datestamp_test",
    srcs = ["datestamp_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "elliptic_fun_test",
    srcs = ["elliptic_fun_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "fast_fun_test",
    srcs = ["fast_fun_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "fft_test",
    srcs = ["fft_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "iir_design_test",
    srcs = ["iir_design_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "logging_test",
    srcs = ["logging_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "math_constants_test",
    srcs = ["math_constants_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "number_util_test",
    srcs = ["number_util_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "phase32_test",
    srcs = ["phase32_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "phasor_rotator_test",
    srcs = ["phasor_rotator_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "q_resampler_test",
    srcs = ["q_resampler_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "q_resampler_kernel_test",
    srcs = ["q_resampler_kernel_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "read_wav_file_generic_test",
    srcs = ["read_wav_file_generic_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "read_wav_file_test",
    srcs = ["read_wav_file_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "serialize_test",
    srcs = ["serialize_test.c"],
    deps = ["//:dsp"],
)

c_test(
    name = "write_wav_file_test",
    srcs = ["write_wav_file_test.c"],
    deps = ["//:dsp"],
)
