/* Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "tactile_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AnalogMicInputConfig, AnalogMicInputConfig, AUTO)

PB_BIND(PdmMicInputConfig, PdmMicInputConfig, AUTO)

PB_BIND(InputConfiguration, InputConfiguration, AUTO)

PB_BIND(PassThroughProcessConfig, PassThroughProcessConfig, AUTO)

PB_BIND(AudioToTactileProcessConfig, AudioToTactileProcessConfig, AUTO)

PB_BIND(ProcessConfiguration, ProcessConfiguration, AUTO)

PB_BIND(SerialOutputConfig, SerialOutputConfig, AUTO)

PB_BIND(TactorsOutputConfig, TactorsOutputConfig, AUTO)

PB_BIND(OutputConfiguration, OutputConfiguration, AUTO)

PB_BIND(OperationMode, OperationMode, AUTO)

PB_BIND(OperationConfig, OperationConfig, AUTO)

PB_BIND(TactorAmplitudes, TactorAmplitudes, AUTO)

PB_BIND(TactorPhases, TactorPhases, AUTO)

PB_BIND(TactorFrequencies, TactorFrequencies, AUTO)

PB_BIND(SupportedOperationModes, SupportedOperationModes, 2)

PB_BIND(Tactor, Tactor, AUTO)

PB_BIND(TactorHardwareLayout, TactorHardwareLayout, 2)

PB_BIND(GetResponse, GetResponse, 2)

PB_BIND(TimeSyncPing, TimeSyncPing, AUTO)

PB_BIND(TimeSyncPong, TimeSyncPong, AUTO)

PB_BIND(TactileMessage, TactileMessage, 2)

PB_BIND(GetRequest, GetRequest, AUTO)

PB_BIND(SetRequest, SetRequest, AUTO)

PB_BIND(StartTimeSyncRequest, StartTimeSyncRequest, AUTO)

PB_BIND(ClientMessage, ClientMessage, 2)
